### PR TITLE
Replace Travis CI with GitHub actions

### LINKED ISSUE #9: Moving from Travis to GitHub Actions
Hello 🙂 

Over the last few months we've been transferring all our CI from Travis to [GitHub Actions (GHA)](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions). We've found that GHA are easier to work with, more reliable, and much much faster. 

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and [shift everything to GHA](https://github.com/exercism/exercism/issues/5396). This issue acts as a call to action if your track is still using Travis. 

For most CI checks this should be a transposing from Travis' syntax to [GHA syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions), and hopefully quite straightforward (see [this PR for an example](https://github.com/exercism/csharp/pull/1338/files)).  However, if you do encounter any issues doing this, please ask on Slack where lots of us now have experience with GHA, or post a comment here and I'll tag relevant people. This would also make a good Hacktoberfest issue for anyone interested in making their first contribution 🙂 

If you've already switched this track to GHA, please feel free to close this issue and ignore it.

Thanks!

### PR DESCRIPTION
**Pull request by cmccandless**
Resolves #9

### CODE REVIEW

**Review by iHiD — APPROVED** [review]

**Comment by cmccandless** [comment]
I made a mistake and deleted my fork before this PR could be merged. If this causes issues, I can recreate it and this PR, just ping me.

**Comment by iHiD** [comment]
@cmccandless If there are tracks where things are approved but you can't merge, please let me know. I approved presuming you could merge at your will, but I'm now unsure if that's the case!

**Comment by cmccandless** [comment]
_I_ was assuming you were waiting on a maintainer to review! 😅

**Comment by iHiD** [comment]
If no-one else has reviewed after like a week, tag me and I'll merge!

**Comment by jaccarmac** [comment]
Yeah sorry about that @cmccandless, (as you can see) I haven't poked at this project in a long while.

**Pull request merged**
