### PR TITLE
🤖 Add file patterns to config.json

### PR DESCRIPTION
**Pull request by ErikSchierboom**
**⚠ This PR requires you to make a simple change before merging. ⚠**

---

To save maintainers from having to manually specify the `files` key in their exercises' `.meta/config.json` files, we are providing support for track-level patterns. See [this PR](https://github.com/exercism/docs/pull/58) for details.

This PR adds (**purposefully wrong**) file patterns to the `config.json` file. It is up to you, the track maintainers, to change these patterns to their correct value.

You can use the following placeholders:
- `%{kebab_slug}`: the `kebab-case` exercise slug (e.g. `bit-manipulation`)
- `%{snake_slug}`: the `snake_case` exercise slug (e.g. `bit_manipulation`)
- `%{camel_slug}`: the `camelCase` exercise slug (e.g. `bitManipulation`)
- `%{pascal_slug}`: the `PascalCase` exercise slug (e.g. `BitManipulation`)

We will soon update `configlet` to enable it to automatically populate the `.meta/config.json` file's `files` property, at which point we will then batch-PR updates to all tracks that have merged this PR.

## Tracking
https://github.com/exercism/v3-launch/issues/19

### CODE REVIEW

**Comment by jaccarmac** [comment]
> This PR requires you to make a simple change,..

Since it's from a different repository, should I do that by creating a fresh pull request and closing this one, or by pull-requesting into your fork?

**Comment by ErikSchierboom** [comment]
@jaccarmac You should be able to just commit to this branch.

**Comment by jaccarmac** [comment]
That wasn't clear on GitHub, but I can see that it works. Thanks!

**Comment by jaccarmac** [comment]
@ErikSchierboom Are the changes I've made reasonable? Using exercism/c#628 as an example, I assumed that the paths are relative to the exercise directory. I don't have exemplars yet, but everything else matches the existing `hello-world` setup.

**Review by jaccarmac — APPROVED** [review]
:+1:

**Comment by ErikSchierboom** [comment]
@jaccarmac Yes, this is perfect! Thanks.

**Comment by ErikSchierboom** [comment]
PR submitted to update the paths in the exercise's meta/config.json files: https://github.com/exercism/shen/pull/34/files

**Pull request merged**
